
from synthetic.naming_convention_camel_case import NamingConventionCamelCase
from synthetic.naming_convention_underscore import NamingConventionUnderscore
from synthetic.decorators import synthesizeMember, synthesizeConstructor
